frequency: 25
model_state_file: 'model.pth'
review_cs: 'data/yel/reviews_with_splits.csv'
save_dir: 'model_storage/ch3/yelp'
vectorizer_file: 'vectorizer.json'
batch_size: 128
learning rate: 0.001
num_epochs: 100
seed: 1337